version: "3.9"

services:
  fastapi:
    build: .
    container_name: chatbot-fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - chatbot-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - chatbot-net
    environment:
      - OLLAMA_NUM_THREADS=8  # кількість потоків CPU

volumes:
  ollama-data:

networks:
  chatbot-net:
